### ISSUE TITLE
Updating wiki after the merge new connection handling (PR#1)

### ISSUE THREAD

**Issue by simoncarrignon** [BIADwiki/BIADwiki#10]
The underlying connection to the server has been slightly changed after #1 and knows rely more o direct interaction between the R script and the MYSQL server. For now, as the port in BIAD main server aren't open, this means more reliance on ssh tunnels. The wiki should be modified to reflect that (and update the explanation for creating a tunnel)

**Comment by AdrianTimpson** [comment]
Wiki now updated accordingly in the Rconnect section
