### ISSUE TITLE
auto_pad trigger fail

### ISSUE THREAD

**Issue by simoncarrignon** [BIADwiki/BIADwiki#13]
https://github.com/BIADwiki/BIADwiki/blob/cd24914abe1b497b3e5d5129d8a3fba276246863/R/auto.make.daily.101.triggers.R#L12-L17
This fail with my machine as there is nothing starting with auto_pad...

**Comment by AdrianTimpson** [comment]
debugged. It deletes the existing triggers before creating new ones

**Comment by simoncarrignon** [comment]
I think it still had a problem but 216de55 should have fied it too!
