### ISSUE TITLE
auto install packages

### ISSUE THREAD

**Issue by simoncarrignon** [BIADwiki/BIADwiki#16]
https://github.com/BIADwiki/BIADwiki/blob/30652304e6b18237ea5a30d75a8ded6d68c6d6e7/R/functions.R#L9-L11
I am not a big fan of the  automatic installing package at the root of the function file... 
As I am not using the open_tunnel funciton, I have no use of `ps`, nor `tools`, packages so it install them for nothein (and I then have to delete them). Not a big big deal but I'd rather not call/use/install pacage when not need.
Using 'require' when (and only when) the package is need seems not a bad, as it throw an error to say to the user 'install the package' and if they need to they can install it. 
Them If we really want the user to have nothing to do, then I would wrap that in a function, and call the function where needed.!

**Comment by AdrianTimpson** [comment]
Agreed, Ive removed
