### ISSUE TITLE
gists

### ISSUE THREAD

**Issue by AdrianTimpson** [BIADwiki/BIADwiki#17]
Hate the gists. Not only is it a wiki.js hack to use iframes, but currently the gists are drawn from a personal account (adrian.timpson).
Not sure what the best solution is yet.

**Comment by simoncarrignon** [comment]
I realised we could simply use the docker I used to load the logs via nginx. 
I started to play with that, so now here: http://biadwiki.org:4321/templates/Sites.csv all templates are uploaded automatically, when biadwiki.sh is run.  So we can refer to these urls in the wiki.

 _(side note, I moved the log here: http://biadwiki.org:4321/logs/ so i could secure the folder 'logs' with password, but not 'templates')_

I think we could put all the thing on the gist there too. If we replace `create.markdown.for.table.content` by [kntir::kable](https://cran.r-project.org/web/packages/kableExtra/vignettes/awesome_table_in_html.html)  we could directly convert the table in html file, send them to a folder manage by the nginx docker (something like : http://biadwiki.org:4321/tables/)
 and link to thes etable.

This **WONT** get rid of the iframes, but at least we won't need @AdrianTimpson personal's GIST/git repo. Happy to giv it a try next week, it hsouldn't be too to complicated to change

I am trying to draw a diagram of the setup I want to do with the dockers, but not easy easy... here is the most comprehensive version I reached so far:
![image](https://github.com/user-attachments/assets/32dd472a-cc72-4944-b642-673125cb2597)

looks scary, but i will find a way to make it clear and simple, and try to present that next week at the COREX meeting :dagger:

**Comment by simoncarrignon** [comment]
I tried two solutions, they both failed, will leave it atm:

Both solution implies rewriting slightly the functions `create.markdown.for.several.tables` and `create.markdown.for.table.content`:
```r
    tmpfile=paste0(file,".rmd")
    html_file <- sub("\\.rmd$", ".html", tmpfile)
    writeLines(text,tmpfile)
    knitr::knit2html(input = tmpfile, output = html_file)
    unlink(tmpfile)
````
This works well, I'have  done it in [replace_gist branch](https://github.com/simoncarrignon/BIADwiki/tree/replace_gist)
simoncarrignon/BIADwiki/replace_gist
simoncarrignon/BIADwiki#d9ce5588a19609144938c48baa5644efb6f9ec97
cf commit d9ce5588a19609144938c48baa5644efb6f9ec97 for exemple. Results is avilable for exemple here: 
http://biadwiki.org:4321/summary_stats/row_counts.html

The problems start when bringing that back to the wiki. 
1. First solution, using directly the nginx docker on the droplet (these links: http://biadwiki.org:4321/summary_stats/row_counts.html)
-> **problem** the docker use only http, I couldn't configure https and firefox (and ohter browser) complain, doesn't like mixed content
![image](https://github.com/user-attachments/assets/f3c675e8-3510-4684-8a81-ca2deff78f9e)

Can t get ssl working with the docker, certbot, letsencrypt, etc...

2. Second solution: using the html file directly in the wiki as asset. 
I added all the file in the script that send asset to the wikijs, it works well, see commit fe608f7804317710bb2cdd27d7a585928604acb8
It is then easy to download the `csv`  files, cf: https://biadwiki.org/strontiumsequences.csv but the `html` don't behave the same and it fails too.
wiki.js try to find it in it's database or something and it gives a page not found error.
Someone proposed this: https://github.com/requarks/wiki/discussions/5435 but couldn't get it work neither... 

Seems that there are solution to make both work, but i will leave it here for the moment.. Gist 1 - 0 Simon.

**Comment by AdrianTimpson** [comment]
Rendering the html within a wiki.js iframe was a trivial security setting change. I've scrapped the create.markdown... functions in favour of the gt package, and replaced with create.html...

**Comment by AdrianTimpson** [comment]
All seems to be working, but I still need to completely remove the gist workflow and files before closing this issue

**Comment by AdrianTimpson** [comment]
A gist workflow and files removed
