### ISSUE TITLE
Remove automatically generated files from git repo, send  them through wiki.js REST API

### ISSUE THREAD

**Issue by simoncarrignon** [BIADwiki/BIADwiki#2]
To keep this repo light we need to remove the images from it, and send them directly from the (a) server (a server with access to database)  to the wiki.  This will involved a few things:

- [ ] rewrite some CRON tasks
- [x] #3  a quick draft here using `httr`:
```r
library(httr)
file <- file("test.png", "rb")
headers <- add_headers(
  Authorization = 'Bearer t*****' #api token
)
url <- 'https://biadwiki.org/u'
body <- list(
  mediaUpload = upload_file("test2.jpg", type = "image/jpg"),
  mediaUpload = '{"folderId":0}'
)
result <- POST(url, headers, body = body)
print(content(result, "text")) #check if it worked
close(file)
```
- [ ] Rewrite git history using filter-branch
- [ ] #4
 
This should lighten a lot the repository, and also remove the reliance on github to deliver the maps/images which will be stored straight on the wiki

**NOTE:** If we set up a webserver as public interface to the dataset, images could be stored there instead of in the wiki

**Comment by simoncarrignon** [comment]
script to wiki has been done already in commit 5f7013f!

**Comment by simoncarrignon** [comment]
Commit [a4faa87]  removed all the images from the `tools/plot` folder on the git repository ; and added all svg and png in the .gitignore. 
This means that nex time the cron is trigger, image won't be available on the repository anymore, and only the one send throught the wiki.js API will be visible.

**Comment by simoncarrignon** [comment]
I update controller.R in a5c2e10d07d2d72855dd44cb31037c4249066149, so if a script fails it stills continue and try the other. The output of this file needs to to be stored somewhere else, maybe a simple html file, on a docker on BIAD.wiki could do? I may try something like that.

**Comment by AdrianTimpson** [comment]
Seems to be working nicely!!
