### ISSUE TITLE
SSH tunnel when connecting to R on MacOS

### ISSUE THREAD

**Issue by AliceRevill** [BIADwiki/BIADwiki#24]
Due to how Sequel Pro and MacOS handle creating a SSH tunnel, it is only available within Sequel Pro and not at a system level. It is possible to create an ssh tunnel using terminal, however, this is unintuitive and a pretty clunky workaround.

The ssh tunnel was handled within R previously, is it possible to add this feature back to the connection function.

**Comment by simoncarrignon** [comment]
Handling the ssh tunnel within R is a bit more messy, as at the end it's just use the terminal in the background, but it then means that R has to deal with the ssh connection PID etc... @AdrianTimpson  did wrote some function to do that but I think it was a bit too much a problem and has removed it is that right? (and different OS will have different SSH version etc....) Maybe we can bring them back (they were deleted here: 0de5d4402e74f682bdf643f6793dc1ef6d7ab95a) but the thing is that ultimately, we will probably not use the ssh tunnel _at all_  and we will probably loose access to macelab-server.biochem.ucl.ac.uk....

A quick reminder that the command in the terminal is simply:
```bash
ssh -N -L 3306:localhost:3306 biad@macelab-server.biochem.ucl.ac.uk -i ~/pathtopem/BIAD-2023-06-01.pem   
```
(you need to know where the ssh key is)
And the tunnel stays  open as long as the terminal open.
To make it even more smooth, I add an alias in my `~/.bashrc`, something like:
```bash
alias tunnel-biad='ssh -N -L 3306:localhost:3306 biad@macelab-server.biochem.ucl.ac.uk -i ~/.ssh/BIAD-2023-06-01.pem'
``` 
So then I just have to run `tunnel-biad` in the terminal, i am sur it would  possible to add an icon or something on mac so you can launch the command directly from the desktop, without even opening a terminal.


Then you will just change the paramaters in you .Renviron to go to the new server and new port and that's it, no PEM file, no ssh tunnel, just your ids for DB access.

**Comment by AliceRevill** [comment]
Thank you, I managed to set up a similar alias in terminal so it's fine for now.

Yeah it makes sense not to worry too much about it right now while you're still developing the final connection method. 

It may be worth adding the command above onto the BIADwiki for people connecting through R in the meantime

**Comment by simoncarrignon** [comment]
I wrapped that here: https://biadwiki.org/en/Connect#create-a-tunnel-via-terminal-linuxmacosbsds, summariisng what I did with @AliceRevill  and @ecanteri , i fyou can have a quick look and tell me if that sounds ok, don't hesitate to correct and add stuff that you needed when you did it, so I can we can close this!
